export const eventAttendeesData = [
  {
    _id: 1,
    name: "Joshua",
    position: "host",
    contact: "01629958550",
    email: "joshua@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 2,
    name: "Emma",
    position: "co-host",
    contact: "01629958551",
    email: "emma@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 3,
    name: "Michael",
    position: "attendee",
    contact: "01629958552",
    email: "michael@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 4,
    name: "Sophia",
    position: "attendee",
    contact: "01629958553",
    email: "sophia@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 5,
    name: "Daniel",
    position: "speaker",
    contact: "01629958554",
    email: "daniel@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 6,
    name: "Olivia",
    position: "attendee",
    contact: "01629958555",
    email: "olivia@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 7,
    name: "James",
    position: "attendee",
    contact: "01629958556",
    email: "james@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 8,
    name: "Ava",
    position: "attendee",
    contact: "01629958557",
    email: "ava@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 9,
    name: "William",
    position: "panelist",
    contact: "01629958558",
    email: "william@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 10,
    name: "Isabella",
    position: "guest",
    contact: "01629958559",
    email: "isabella@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 11,
    name: "Joshua",
    position: "host",
    contact: "01629958550",
    email: "joshua@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 12,
    name: "Emma",
    position: "co-host",
    contact: "01629958551",
    email: "emma@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 13,
    name: "Michael",
    position: "attendee",
    contact: "01629958552",
    email: "michael@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 14,
    name: "Sophia",
    position: "attendee",
    contact: "01629958553",
    email: "sophia@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 15,
    name: "Daniel",
    position: "speaker",
    contact: "01629958554",
    email: "daniel@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 16,
    name: "Olivia",
    position: "attendee",
    contact: "01629958555",
    email: "olivia@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 17,
    name: "James",
    position: "attendee",
    contact: "01629958556",
    email: "james@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 18,
    name: "Ava",
    position: "attendee",
    contact: "01629958557",
    email: "ava@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 19,
    name: "William",
    position: "panelist",
    contact: "01629958558",
    email: "william@gmail.com",
    image: "/attendeesProfile.png",
  },
  {
    _id: 20,
    name: "Isabella",
    position: "guest",
    contact: "01629958559",
    email: "isabella@gmail.com",
    image: "/attendeesProfile.png",
  },
];
