export const churchData = [
  { _id: 1, name: "Hope Community Church", image: "/church1.png" },
  { _id: 2, name: "Grace Chapel", image: "/church2.png" },
  { _id: 3, name: "Faith Baptist Church", image: "/church3.png" },
  { _id: 4, name: "New Life Church", image: "/church4.png" },
  { _id: 5, name: "Trinity Lutheran Church", image: "/church1.png" },
  { _id: 6, name: "St. Paul's Episcopal Church", image: "/church2.png" },
  { _id: 7, name: "Calvary Baptist Church", image: "/church3.png" },
  { _id: 8, name: "Bethany United Methodist Church", image: "/church4.png" },
  { _id: 9, name: "Christ the King Church", image: "/church1.png" },
  { _id: 10, name: "Living Water Church", image: "/church2.png" },
  { _id: 11, name: "First Congregational Church", image: "/church3.png" },
  { _id: 12, name: "Mount Zion Church", image: "/church4.png" },
  { _id: 13, name: "Unity Church", image: "/church1.png" },
  { _id: 14, name: "Holy Spirit Church", image: "/church2.png" },
  { _id: 15, name: "St. Matthew's Church", image: "/church3.png" },
  { _id: 16, name: "Cornerstone Church", image: "/church4.png" },
  { _id: 17, name: "Harvest Church", image: "/church1.png" },
  { _id: 18, name: "Immanuel Church", image: "/church2.png" },
  { _id: 19, name: "Radiant Church", image: "/church3.png" },
  { _id: 20, name: "The River Church", image: "/church4.png" },
];
