export const churchData = [
  {
    _id: 1,
    name: "Hope Community Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "A welcoming community focused on hope and faith.",
  },
  {
    _id: 2,
    name: "Grace Chapel",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "A place of grace where everyone is accepted.",
  },
  {
    _id: 3,
    name: "Faith Baptist Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "A Baptist church dedicated to faith, family, and fellowship.",
  },
  {
    _id: 4,
    name: "New Life Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "Experience a new life through Jesus Christ.",
  },
  {
    _id: 5,
    name: "Trinity Lutheran Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "A vibrant Lutheran community nurturing faith.",
  },
  {
    _id: 6,
    name: "St. Paul's Episcopal Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "An Episcopal church committed to serving the community.",
  },
  {
    _id: 7,
    name: "Calvary Baptist Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "A community of believers sharing God's love.",
  },
  {
    _id: 8,
    name: "Bethany United Methodist Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "Where faith, hope, and love unite.",
  },
  {
    _id: 9,
    name: "Christ the King Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "Honoring Christ as our leader and savior.",
  },
  {
    _id: 10,
    name: "Living Water Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "Flowing with the spirit of life and renewal.",
  },
  {
    _id: 11,
    name: "First Congregational Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "A welcoming congregational community for all.",
  },
  {
    _id: 12,
    name: "Mount Zion Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "A church focusing on spiritual growth and community.",
  },
  {
    _id: 13,
    name: "Unity Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "Unity in diversity, grounded in love.",
  },
  {
    _id: 14,
    name: "Holy Spirit Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "Empowered by the Holy Spirit to serve.",
  },
  {
    _id: 15,
    name: "St. Matthew's Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "Rooted in Matthew's teachings of love and compassion.",
  },
  {
    _id: 16,
    name: "Cornerstone Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "A cornerstone of faith in the community.",
  },
  {
    _id: 17,
    name: "Harvest Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "Reaping the harvest of spiritual growth and community.",
  },
  {
    _id: 18,
    name: "Immanuel Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "God is with us in our journey of faith.",
  },
  {
    _id: 19,
    name: "Radiant Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "Radiating love and light in the community.",
  },
  {
    _id: 20,
    name: "The River Church",
    image: ["/church-image.png", "/church-2.jpg"],
    description: "Flowing together in the spirit and mission.",
  },
];
