export const eventData = [
  {
    _id: 1,
    name: "Community Outreach Day",
    hostName: "Grace Community Church Outreach Team",
    location: "Main Hall, Grace Community Church",
    date: "Dec 2, 2023, 10:00 AM - 2:00 PM",
    image: ["/event.png"],
  },
  {
    _id: 2,
    name: "Food Drive for Families in Need",
    hostName: "Local Food Bank",
    location: "City Park Pavilion",
    date: "Dec 3, 2023, 9:00 AM - 5:00 PM",
    image: ["/event.png"],
  },
  {
    _id: 3,
    name: "Health and Wellness Fair",
    hostName: "City Health Department",
    location: "Community Center Gym",
    date: "Dec 10, 2023, 11:00 AM - 4:00 PM",
    image: ["/event.png"],
  },
  {
    _id: 4,
    name: "Winter Clothing Drive",
    hostName: "Neighborhood Association",
    location: "City Hall Parking Lot",
    date: "Dec 15, 2023, 10:00 AM - 3:00 PM",
    image: ["/event.png"],
  },
  {
    _id: 5,
    name: "Community Garden Planting Day",
    hostName: "Green Thumb Collective",
    location: "Community Garden on Elm St.",
    date: "Dec 16, 2023, 9:00 AM - 1:00 PM",
    image: ["/event.png"],
  },
  {
    _id: 6,
    name: "Holiday Toy Giveaway",
    hostName: "Local Charity Organization",
    location: "Main Hall, Community Center",
    date: "Dec 20, 2023, 1:00 PM - 5:00 PM",
    image: ["/event.png"],
  },
  {
    _id: 7,
    name: "Mental Health Awareness Workshop",
    hostName: "Wellness Advocates Group",
    location: "Library Meeting Room",
    date: "Dec 22, 2023, 2:00 PM - 4:00 PM",
    image: ["/event.png"],
  },
  {
    _id: 8,
    name: "New Year’s Community Clean-Up",
    hostName: "Clean City Initiative",
    location: "Downtown Square",
    date: "Jan 5, 2024, 10:00 AM - 1:00 PM",
    image: ["/event.png"],
  },
  {
    _id: 9,
    name: "Winter Festival of Lights",
    hostName: "Local Arts Council",
    location: "Riverside Park",
    date: "Jan 12, 2024, 5:00 PM - 9:00 PM",
    image: ["/event.png"],
  },
  {
    _id: 10,
    name: "Youth Empowerment Workshop",
    hostName: "Teen Leadership Coalition",
    location: "High School Auditorium",
    date: "Jan 15, 2024, 3:00 PM - 6:00 PM",
    image: ["/event.png"],
  },
];
