export const memberData = [
  {
    _id: 1,
    name: "Brother James Carter",
    designation: "Biblical Studies Professor and Author",
    churchName: "Hope Community Church",
    expert: "Web Development",
    image: "/member.png",
  },
  {
    _id: 2,
    name: "Brother James Carter",
    designation: "Biblical Studies Professor and Author",
    churchName: "Hope Community Church",
    expert: "Web Development",
    image: "/member.png",
  },
  {
    _id: 3,
    name: "Brother James Carter",
    designation: "Biblical Studies Professor and Author",
    churchName: "Hope Community Church",
    expert: "Mobile App Development",
    image: "/member.png",
  },
  {
    _id: 4,
    name: "Brother James Carter",
    designation: "Biblical Studies Professor and Author",
    churchName: "Hope Community Church",
    expert: "Web Development",
    image: "/member.png",
  },
  {
    _id: 5,
    name: "Brother James Carter",
    designation: "Biblical Studies Professor and Author",
    churchName: "Hope Community Church",
    expert: "Web Development",
    image: "/member.png",
  },
  {
    _id: 6,
    name: "Brother James Carter",
    designation: "Biblical Studies Professor and Author",
    churchName: "Hope Community Church",
    expert: "Web Development",
    image: "/member.png",
  },
];
