export const prayerData = [
  {
    _id: 1,
    image: "/profileImage.png",
    name: "Richa Chawal",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 2,
    image: "/profileImage.png",
    name: "Amit Sharma",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 3,
    image: "/profileImage.png",
    name: "Sneha Patel",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 4,
    image: "/profileImage.png",
    name: "Rajiv Kumar",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 5,
    image: "/profileImage.png",
    name: "Priya Singh",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 6,
    image: "/profileImage.png",
    name: "Vikram Mehta",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 7,
    image: "/profileImage.png",
    name: "Neha Joshi",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 8,
    image: "/profileImage.png",
    name: "Karan Verma",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 9,
    image: "/profileImage.png",
    name: "Simran Kaur",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 10,
    image: "/profileImage.png",
    name: "Anil Gupta",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 11,
    image: "/profileImage.png",
    name: "Riya Bansal",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 12,
    image: "/profileImage.png",
    name: "Suresh Yadav",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 13,
    image: "/profileImage.png",
    name: "Meera Nair",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 14,
    image: "/profileImage.png",
    name: "Deepak Reddy",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
  {
    _id: 15,
    image: "/profileImage.png",
    name: "Nisha Roy",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    date: "Dec 20, 2024",
    prayerName: "Divine Beginnings for us…",
    description:
      "Please pray about a situation where people on a certain place continuously harass people and make them believe God isn't with them. Please pray for the Holy Spirit to convict them and for God to ",
    churchName: "Grace Fellowship Church",
  },
];
