export const requestData = [
  {
    _id: 1,
    name: "Emily Johnson",
    designation: "Certified Christian Counselor and Family Ministry Leader",
    churchName: "Hope Community Church",
    status: "Pending",
    image: "/requestImage.png",
  },
  {
    _id: 2,
    name: "Michael Smith",
    designation: "Youth Pastor",
    churchName: "Grace Fellowship",
    status: "Pending",
    image: "/requestImage.png",
  },
  {
    _id: 3,
    name: "Sarah Brown",
    designation: "Worship Leader",
    churchName: "Faith Community Church",
    status: "Pending",
    image: "/requestImage.png",
  },
  {
    _id: 4,
    name: "David Wilson",
    designation: "Children’s Ministry Coordinator",
    churchName: "Living Waters Church",
    status: "Pending",
    image: "/requestImage.png",
  },
  {
    _id: 5,
    name: "Linda Davis",
    designation: "Community Outreach Director",
    churchName: "Victory Church",
    status: "Pending",
    image: "/requestImage.png",
  },
];
