export const resourcesData = [
  {
    _id: 1,
    name: "3D Model of Interior Redesign",
    creator: "Sister Mary Agnes",
    churchName: "Grace Fellowship Church",
    services: "Digital Service",
    image: "/resourcesImage.png",
  },
  {
    _id: 2,
    name: "Children's Activity Kit",
    creator: "Brother John Doe",
    churchName: "Hope Community Church",
    services: "In-Person Event",
    image: "/resourcesImage.png",
  },
  {
    _id: 3,
    name: "Virtual Bible Study Guide",
    creator: "Sister Anne",
    churchName: "Faithful Disciples Church",
    services: "Online Service",
    image: "/resourcesImage.png",
  },
  {
    _id: 4,
    name: "Community Outreach Program",
    creator: "Pastor Mark Smith",
    churchName: "Shining Light Church",
    services: "Community Service",
    image: "/resourcesImage.png",
  },
  {
    _id: 5,
    name: "Youth Empowerment Workshop",
    creator: "Sister Sarah Jones",
    churchName: "Unity Church",
    services: "Workshop",
    image: "/resourcesImage.png",
  },
  {
    _id: 6,
    name: "Online Worship Playlist",
    creator: "Brother David Lee",
    churchName: "Evergreen Church",
    services: "Digital Service",
    image: "/resourcesImage.png",
  },
  {
    _id: 7,
    name: "Church Gardening Initiative",
    creator: "Sister Emily White",
    churchName: "Green Pastures Church",
    services: "Community Service",
    image: "/resourcesImage.png",
  },
  {
    _id: 8,
    name: "Prayer Retreat Guide",
    creator: "Pastor Linda Green",
    churchName: "Holy Family Church",
    services: "Retreat",
    image: "/resourcesImage.png",
  },
  {
    _id: 9,
    name: "Devotional Booklet",
    creator: "Brother Samuel Black",
    churchName: "Covenant Church",
    services: "Print Material",
    image: "/resourcesImage.png",
  },
];
